Remove local registry config so I dont get an error on initial install
Otherwise I get this error when installing for the first time

```
conda activate jupyterlab-data-explorer
jlpm install
yarn install v1.15.2
[1/4] 🔍  Resolving packages...
error Couldn't find package "@jupyterlab/application@^1.0.0" required by "@jupyterlab/dataregistry-csvviewer-extension@0.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning workspace-aggregator-4012d5a9-bf71-42b6-9a7f-f1eae0bda212 > @jupyterlab/dataregistry > rxjs-spy > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning workspace-aggregator-4012d5a9-bf71-42b6-9a7f-f1eae0bda212 > @jupyterlab/dataregistry-extension > @nteract/data-explorer > semiotic > prop-types > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning workspace-aggregator-4012d5a9-bf71-42b6-9a7f-f1eae0bda212 > @jupyterlab/dataregistry > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
Error: Couldn't find package "@jupyterlab/application@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/application@^1.0.0" required by "@jupyterlab/dataregistry-registry-extension@0.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/csvviewer@^1.0.0" required by "@jupyterlab/dataregistry-csvviewer-extension@0.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/csvviewer@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/apputils@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/filebrowser@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/notebook@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/coreutils@^3.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/coreutils@^3.0.0" required by "@jupyterlab/dataregistry-registry-extension@0.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/docmanager@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/docregistry@^1.0.4" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Couldn't find package "@jupyterlab/rendermime@^1.0.0" required by "@jupyterlab/dataregistry-extension@3.0.0" on the "npm" registry.
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:310:30)
    at /usr/local/miniconda3/envs/jupyterlab-data-explorer/lib/python3.6/site-packages/jupyterlab/staging/yarn.js:323:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```